apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-selenium
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "namu-wiki.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.selenium.replicas }}
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
          {{- include "namu-wiki.labels" . | nindent 8 }}
    spec:
      containers:
        - name: selenium
          image: "{{ .Values.selenium.image.repository }}:{{ .Values.selenium.image.tag }}"
          ports:
            - containerPort: {{ .Values.selenium.service.port }}