apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: namu-wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
      - name: scheduler
        image: apache/airflow:2.10.4
        command: ["airflow", "scheduler"]
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-webserver-dags-0