apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: namu-wiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow
      component: worker
  template:
    metadata:
      labels:
        app: airflow
        component: worker
    spec:
      containers:
      - name: worker
        image: apache/airflow:2.10.4
        command: ["airflow", "celery", "worker"]
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-webserver-dags-0